import typography from '@tailwindcss/typography';

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#02010A",
        "surface": "#141120",
        "surface-dim": "#141120",
        "surface-bright": "#3a3747",
        "surface-container-lowest": "#0f0c1b",
        "surface-container-low": "#1c1a29",
        "surface-container": "#201e2d",
        "surface-container-high": "#2b2838",
        "surface-container-highest": "#363343",
        "surface-variant": "#363343",
        "surface-tint": "#e9c400",
        "primary": "#fff6df",
        "primary-container": "#ffd700",
        "primary-fixed": "#ffe16d",
        "primary-fixed-dim": "#e9c400",
        "secondary": "#d0c6ab",
        "secondary-container": "#4f4934",
        "secondary-fixed": "#ede2c6",
        "secondary-fixed-dim": "#d0c6ab",
        "tertiary": "#fff5de",
        "tertiary-container": "#f6d865",
        "tertiary-fixed": "#ffe16e",
        "tertiary-fixed-dim": "#e1c554",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-primary": "#3a3000",
        "on-primary-container": "#705e00",
        "on-primary-fixed": "#221b00",
        "on-primary-fixed-variant": "#544600",
        "on-secondary": "#36301d",
        "on-secondary-container": "#c1b89d",
        "on-secondary-fixed": "#201b0a",
        "on-secondary-fixed-variant": "#4d4632",
        "on-tertiary": "#3a3000",
        "on-tertiary-container": "#705d00",
        "on-tertiary-fixed": "#221b00",
        "on-tertiary-fixed-variant": "#544600",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "on-surface": "#e6dff5",
        "on-surface-variant": "#d0c6ab",
        "on-background": "#e6dff5",
        "outline": "#999077",
        "outline-variant": "#4d4732",
        "inverse-surface": "#e6dff5",
        "inverse-on-surface": "#312e3e",
        "inverse-primary": "#705d00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['"Space Grotesk"', 'sans-serif'],
        heading: ['"Space Grotesk"', 'sans-serif'],
      },
    },
  },
  plugins: [
    typography,
  ],
}
